{% set name = "flaskwebgui" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 786d46dc1be65e6bb46b5aa4a0eb3af7d531769cb756fb7a442a64d3595ee72a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flask
    - waitress
    - whichcraft
    - psutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - flaskwebgui

about:
  home: https://github.com/ClimenteA/flaskwebgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create desktop applications with Flask/FastAPI/Django!
  dev_url: https://github.com/ClimenteA/flaskwebgui

extra:
  recipe-maintainers:
    - melund
