{% set name = "flaskwebgui" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a6f3aefbb6747c9743209191c1ba14d6b84a80d591014c2011e191c2c8f67c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - flask
    - waitress
    - whichcraft
    - psutil

test:
  imports:
    - flaskwebgui

about:
  home: https://github.com/ClimenteA/flaskwebgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create desktop applications with Flask/FastAPI/Django!
  dev_url: https://github.com/ClimenteA/flaskwebgui

extra:
  recipe-maintainers:
    - melund
