{% set name = "flaskwebgui" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cae89d5da9ff518dc0d5a4c207c3d73304fa5aeec3880c7a60c4e8b313e76aa3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - flask
    - waitress
    - whichcraft
    - psutil

test:
  imports:
    - flaskwebgui

about:
  home: https://github.com/ClimenteA/flaskwebgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create desktop applications with Flask/FastAPI/Django!
  dev_url: https://github.com/ClimenteA/flaskwebgui

extra:
  recipe-maintainers:
    - melund
