{% set name = "flaskwebgui" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a5dfea6bb58479beced817cb3c7adeffba7f4965273c1cb00f728aeb9566ce1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - flask
    - waitress
    - whichcraft
    - psutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - flaskwebgui

about:
  home: https://github.com/ClimenteA/flaskwebgui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create desktop applications with Flask/FastAPI/Django!
  dev_url: https://github.com/ClimenteA/flaskwebgui

extra:
  recipe-maintainers:
    - melund
